owner: R3Group-Digital # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Portal
    url: https://portal.r3-group.app
    maxResponseTime: 1000
  - name: Tembo Tool App
    url: https://app.tembo-tool.io/
  - name: Tembo Tool Site
    url: https://tembo-tool.io/
  - name: SSO
    url: https://sso.r3-group.app/
  - name: Design System
    url: https://design.r3-group.app/
  - name: Diag
    url: https://diag-rse.r3-group.app/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: R3 Status
  introTitle: "**R3 Status** est une page open-source de monitoring de la plate-forme digital de R3."
  introMessage: Cette page affiche de la donnée en temps réel depuis notre repository Upptime sur [GitHub repository](https://github.com/R3Group-Digital/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
