owner: R3Group-Digital # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: R3 Portal
    url: https://portal.r3-group.app
    maxResponseTime: 1000
  - name: R3 Access Management (SSO)
    url: https://sso.r3-group.app/
  - name: R3 Design System
    url: https://design.r3-group.app/
  - name: R3 Pilot RSE (Tembo Tool) 
    url: https://app.tembo-tool.io/
  - name: Diag RSE
    url: https://diag-rse.r3-group.app/
  - name: R3 Pilot Carbon
    url: https://r3-carbone.climatip.fr

assignees:
  - adrienwb
  - Kiwwwi
  - Khazeral

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.r3-group.app
  #baseUrl: /upptime
  name: R3 Status
  theme: light
  logoUrl: https://portal.r3-group.app/bloc_marque.png
  faviconSvg: https://portal.r3-group.app/logo.svg
  introTitle: "**R3 Status** est une page open-source de monitoring de la plate-forme digitale de R3."
  introMessage: Cette page affiche de la donnée en temps réel depuis notre repository Upptime sur [GitHub repository](https://github.com/R3Group-Digital/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Made with ❤️ by [R3 Group]($REPO), 🔌 by [Upptime.](https://github.com/upptime/upptime)
